[package]
name = "unityrust"
version = "0.1.0"
edition = "2018"

[lib]
name = "unity_rust"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
